import '@/app/globals.css';
import { cn } from '@/lib/utils';
import NextAuthSessionProvider from '@/providers/SessionProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

const appName = `${process.env.NEXT_APP_NAME}`;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, 'bg-[#f3f3f3] dark:bg-[#313338]')}
        suppressHydrationWarning={true}
      >
        <NextAuthSessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey={appName}
          >
            <main>
              <div>{children}</div>
            </main>
          </ThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
