export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
